<?php /** @noinspection PhpUnused */

declare(strict_types=1);

/**
 * Autogenerated!
 *
 * @table stats
 */
class User{

    /**
     * @column user
     * @column_type varchar
     * @var string
     */
    private $user;

    /**
     * @column firstlogin
     * @column_type int
     * @converter IntToDateTimeConverter
     * @var DateTime
     */
    private $firstLoginDate;

    /**
     * @column lastlogin
     * @column_type int
     * @converter IntToDateTimeConverter
     * @var DateTime
     */
    private $lastLoginDate;

    /**
     * @result string
     */
    public function getUser() : string{
        return $this->user;
    }

    /**
     * @param string $user
     *
     * @return void
     */
    public function setUser(string $user) : void{
        $this->user = $user;
    }

    /**
     * @result DateTime
     */
    public function getFirstLoginDate() : DateTime{
        return $this->firstLoginDate;
    }

    /**
     * @param DateTime $firstLoginDate
     *
     * @return void
     */
    public function setFirstLoginDate(DateTime $firstLoginDate) : void{
        $this->firstLoginDate = $firstLoginDate;
    }

    /**
     * @result DateTime
     */
    public function getLastLoginDate() : DateTime{
        return $this->lastLoginDate;
    }

    /**
     * @param DateTime $lastLoginDate
     *
     * @return void
     */
    public function setLastLoginDate(DateTime $lastLoginDate) : void{
        $this->lastLoginDate = $lastLoginDate;
    }
}